version: "3.7"

services:
  test-service:
      build:
        context: ./Test_service
        dockerfile: dockerfile
      ports:
        - "8084:8084"
      networks:
        - back-tier-network
      depends_on:
        - mysqldb-service
  user-service:
      build:
        context: ./User_service
        dockerfile: dockerfile
      ports:
        - "8083:8083"
      networks:
        - back-tier-network
      depends_on:
        - mysqldb-service
  mysqldb-service:
    image: mysql:latest
    networks:
      - back-tier-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=  

networks:
  back-tier-network:
    driver: bridge