version: "3.7"

services:
  # Frontend Service
  app-client:
    build:
      context: ./psych_eval-fe
      dockerfile: dockerfile.dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - test-service
      - user-service
    networks:
      - frontend-network
  #Backend Services
  mysql-service:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=kkk
    networks:
      - backend-network
  test-service:
    build:
      context: ./Test_service
      dockerfile: dockerfile.dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/projet_jee?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - mysql-service
  user-service:
    build:
      context: ./User_service
      dockerfile: dockerfile.dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/projet_jee?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - mysql-service
networks:
  backend-network:
    driver: bridge
  frontend-network: